"""add tier_summary to recipe_tiers

Revision ID: 2f0b7277e2eb
Revises: 34c088513f1f
Create Date: 2026-08-25 01:37:53.589281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0b7277e2eb'
down_revision = '34c088513f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_tiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_summary', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_tiers', schema=None) as batch_op:
        batch_op.drop_column('tier_summary')

    # ### end Alembic commands ###
