"""add dishes, recipe_tiers, food_items

Revision ID: 3337792f1e38
Revises: 551d8171b9a6
Create Date: 2026-08-24 21:39:27.902489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3337792f1e38'
down_revision = '551d8171b9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('cuisine', sa.String(length=80), nullable=True),
    sa.Column('meal_type', sa.String(length=40), nullable=True),
    sa.Column('methods', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('names', sa.JSON(), nullable=True),
    sa.Column('per_100g', sa.JSON(), nullable=False),
    sa.Column('grams_per_unit', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('recipe_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('serves', sa.Integer(), nullable=True),
    sa.Column('time_min', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('diet_flags', sa.JSON(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('prep', sa.JSON(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'level', 'lang', name='uq_dish_level_lang')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tiers')
    op.drop_table('food_items')
    op.drop_table('dishes')
    # ### end Alembic commands ###
