"""add recipe content snapshots, snapshot fields on cook_logs, skills and lessons

Revision ID: 934151c00718
Revises: d4435c97466d
Create Date: 2026-09-06 13:12:57.854416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934151c00718'
down_revision = 'd4435c97466d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_content_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_slug', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_slug', 'level', 'lang', 'content_digest', name='uq_snapshot_content')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('dish_slug', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('step_id', sa.String(length=80), nullable=False),
    sa.Column('next_practice_dish_slug', sa.String(length=80), nullable=True),
    sa.Column('next_practice_level', sa.String(length=20), nullable=True),
    sa.Column('next_practice_reason', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('cook_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('snapshot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cook_logs_snapshot_id_recipe_content_snapshots', 'recipe_content_snapshots', ['snapshot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cook_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cook_logs_snapshot_id_recipe_content_snapshots', type_='foreignkey')
        batch_op.drop_column('snapshot_id')
        batch_op.drop_column('lang')

    op.drop_table('lessons')
    op.drop_table('skills')
    op.drop_table('recipe_content_snapshots')
    # ### end Alembic commands ###
