"""add session_id to cook_logs

Revision ID: d4435c97466d
Revises: 51468a1638ea
Create Date: 2026-09-06 11:15:52.920656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4435c97466d'
down_revision = '51468a1638ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cook_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_user_session_cooklog', ['user_id', 'session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cook_logs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_session_cooklog', type_='unique')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
