export const planningStrings = {
  en: {
    title: 'Plan', plans: 'Meal plans', events: 'Events', home: 'Home', legacy: 'Saved legacy plans',
    appearanceTitle: 'Account appearance', appearanceAccount: 'Signed-in language and theme are saved to your account. Guest settings stay on this device.', appearanceReview: 'Review account appearance settings', appearanceOtherSave: 'Finish the pending save in Planning or Shopping before changing account settings.', appearanceRetryChange: 'Reload your saved settings, then close this window and choose the change again.',
    foundation: 'Planning foundation', foundationBody: 'Your plans, shopping lists and templates are private and saved to your account. Choose dishes when published catalog entries are available. Starting guided cooking from a planned configuration is not available yet.',
    foundationSummary: 'About your private planning', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark',
    period_current: 'Current', period_upcoming: 'Upcoming', period_past: 'Past',
    shoppingCapacity: 'This change would make your saved shopping selections too large. Nothing was changed. Remove an old selection or choose fewer meals, then try again. Your plans remain saved.',
    shopping: 'Shopping', templates: 'Templates', templateName: 'Template name', templateSave: 'Save as template', templateApply: 'Add from template', templateManage: 'Manage templates', templateEmpty: 'No saved templates yet.', templateChoose: 'Choose a saved template', templateIndependent: 'Adds independent copies. Dates, links, reminders and shopping checks are not copied.',
    'template.delete': 'Delete template', 'template.rename': 'Rename template', 'shopping.personal.delete': 'Remove shopping item',
    moveEffect: 'The meal moves to the selected date. Shopping selections that no longer refer to this plan are removed; undo restores their saved state.',
    personalDeleteEffect: 'Only the selected personal shopping addition is removed. The remaining shopping selections are kept.',
    shoppingSnapshotEffect: 'These saved selections are retained for undo. Valid selections are recalculated; invalid selections are removed together with their checks, extras and personal additions.',
    effectsShopping_scopes: 'Saved shopping selections', effectsTemplates: 'Templates', unit_taste: 'to taste',
    shoppingSelectionsRemoved: 'Shopping selections removed', shoppingSelectionLoss: 'These selections will no longer be valid. Their checkmarks, extras and personal additions will be removed too. Undo restores them together.',
    shoppingSelectionCounts: '{checks} saved checks · {extras} extras · {personal} personal additions',
    'shopping.scope.delete': 'Remove saved shopping selection', scopeDeleteEffect: 'Only this shopping selection is removed. Your plan, event and recipes remain unchanged.',
    'item.create': 'Add item', 'item.update': 'Edit item', 'item.delete': 'Remove item', 'item.move': 'Move item', 'item.copy': 'Copy item',
    'plan.copy': 'Plan again', 'event.copy': 'Event again',
    planAgainNote: 'Creates an independent plan starting on your chosen day. Meals and linked occasions are copied with new identities; preparation reminders start unchecked. The original stays unchanged.',
    eventAgainNote: 'Creates an independent occasion with its menu and guest count. Preparation reminders start unchecked and no plan links are copied. The original stays unchanged.',
    account_deleted: 'This account has been deleted. Planning writes are blocked. Return to account settings to review the account state.',
    account_deletion_pending: 'Account deletion has an unresolved outcome. Planning writes are blocked and uncertain saves are kept. Return to account settings to review deletion.',
    reviewAccountSettings: 'Review account settings',
    itemKind: 'What would you like to add?', menu: 'Menu', publishedDish: 'Published dish', dishOption: 'Recipe option',
    catalogEmpty: 'No published dishes are available in this language. You can add a personal item or a note.',
    catalogUnavailable: 'This exact dish or option is unavailable. Your saved reference is kept; no replacement has been selected.',
    loadingItems: 'Loading…', retryRead: 'Reload details', itemPreview: 'Dish preview', authoredPreview: 'Preview published content',
    authoredFor: 'Authored quantities for', resolvedFor: 'Saved quantities for', servings: 'Servings', servingsCount: 'servings', guestsCount: 'guests', followsGuests: 'Follow guest count',
    servingsInvalid: 'Enter a whole number of servings from 1 to 1000.', quantityInvalid: 'Provide both quantity and unit, or clear both. Use a positive quantity up to 1,000,000 with at most three decimal places.',
    optionalQuantity: 'Quantity (optional)', unit: 'Unit', optionalGroup: 'Group (optional)', contribution: 'Brought by / contribution (optional)',
    contributionHelp: 'A named contribution is excluded from your shopping list.', contributionExcluded: 'Contribution; excluded from your shopping',
    destinationType: 'Destination type', itemDestination: 'Destination meal or event', noItemTargets: 'Choose a plan with a meal, or an event. Create a destination first if needed.',
    itemTransferNote: 'Choose the destination explicitly. Moving to a meal keeps the saved servings and stops following guest count.',
    ingredients: 'Ingredients', equipment: 'Equipment', method: 'Method', minutes: 'minutes',
    planningExample: 'Planning example: illustrative quantities, not a cooking guide.', previewOnly: 'Preview only. Starting guided cooking from this configuration is not available yet.',
    unit_piece: 'pieces', unit_head: 'heads', unit_loaf: 'loaves', unit_bunch: 'bunches', unit_pack: 'packs', unit_tsp: 'tsp', unit_tbsp: 'tbsp',
    formChanged: 'Planning changed while this form was open. Your entries are kept. Review the latest saved values before saving your changes.',
    latestValues: 'Latest saved values', reviewLatest: 'Keep my entries and use the latest revision',
    loading: 'Loading your plans…', signIn: 'Sign in to open your private plans.', signInAction: 'Sign in',
    reload: 'Reload plans', saved: 'Saved to your account.', saving: 'Saving…', cancel: 'Cancel', close: 'Close', save: 'Save changes',
    backPlans: 'All meal plans', backEvents: 'All events', emptyPlans: 'Make room for a few meals.', emptyPlansBody: 'Choose your dates, then add meals whenever you need them.',
    emptyEvents: 'Plan your next occasion.', emptyEventsBody: 'Give it a date and keep your preparation reminders together.',
    'plan.create': 'New meal plan', 'plan.rename': 'Rename plan', 'plan.resize': 'Change dates', 'plan.delete': 'Delete plan',
    'meal.create': 'Add meal', 'meal.update': 'Edit meal', 'meal.move': 'Move meal', 'meal.copy': 'Copy meal', 'meal.delete': 'Delete meal',
    'event.create': 'New event', 'event.update': 'Edit event', 'event.link': 'Link event to plan', 'event.delete': 'Delete event', 'event.unlink': 'Unlink event',
    'task.create': 'Add reminder', 'task.update': 'Edit reminder', 'task.delete': 'Delete reminder',
    name: 'Name', optionalName: 'Meal name (optional)', start_date: 'First day', end_date: 'Last day', date: 'Date', time: 'Time (optional)', guests: 'Guests',
    plan_id: 'Meal plan', event_id: 'Event', text: 'Reminder', bucket: 'When', done: 'Done', earlier: 'Ahead of time', day: 'On the day', serving: 'Before serving',
    preparation: 'Preparation', preparationNote: 'Personal reminders for the occasion. Check them off as you go.', noTasks: 'No reminders here yet.',
    meal: 'Meal', openDay: 'Room for something good.', mealFoundation: 'Recipes and dish items are coming next.',
    previous: 'Previous three days', next: 'Next three days', dateNavigation: 'Plan dates', jump: 'Go to date', actions: 'Actions',
    outside: 'Linked events outside these dates', linkedEvent: 'Linked event', eventIdentity: 'This is one event wherever it is linked. Editing it updates every linked plan.',
    noTargets: 'Create a meal plan and an event before linking them.', noPlans: 'Create a destination plan first.', choose: 'Choose…',
    review: 'Review change', reviewBody: 'These are the exact records affected by this change.', confirm: 'Confirm change',
    effectsPlans: 'Plans', effectsMeals: 'Meals', effectsEvents: 'Events', effectsLinks: 'Event links', effectsTasks: 'Reminders', effectsItems: 'Items and notes',
    kind_dish: 'Dish', kind_personal: 'Personal item', kind_note: 'Note',
    preserved: 'The linked events themselves are kept.', outsidePreview: 'Linked events outside the new dates', recordDetails: 'Record details',
    resizeEffect: 'The plan dates change. Meals listed below are removed; event links are kept.', deleteEffect: 'The listed records are removed.',
    expires: 'Review expires', stalePreview: 'This review has expired or planning has changed. Close it, reload and review again.',
    undo: 'Undo', undoNote: 'Available until another change or the displayed expiry.',
    pending: 'The last save has an uncertain outcome. Retry the same save to find out whether it completed.',
    rejected: 'The last save was rejected. Review its details, then discard it and reload before making a new change.',
    retry: 'Retry the same save', discard: 'Discard rejected save and reload', pendingDetails: 'Review submitted change',
    request: 'Change', status: 'Response status', error: 'We could not complete this request. Reload and try again.',
    storageError: 'Recovery storage is unavailable or unreadable. Saving is blocked; your saved plans remain on your account.',
    revisionError: 'Planning changed during loading. Reload to get a consistent view before editing.',
    lockError: 'Another tab is saving. Wait for it to finish, then reload.', lockUnavailable: 'This browser cannot coordinate safe saves between tabs. Use a browser with Web Locks support.',
    sessionError: 'Your session changed or expired. Sign in again to continue.',
    required: 'Enter a name or reminder.', range: 'Choose a range of 1 to 730 days.', invalid_date: 'Choose a valid date.',
    notFound: 'This plan or event is no longer available.', review_required: 'The save was rejected. Review the submitted change below before discarding the rejected attempt. Your form entries are kept.',
    previewUnsupported: 'Change previews are not available yet. Reload after the planning update.',
    localFields: 'Review the fields below. Nothing is saved until the server confirms it.',
  },
  de: {
    title: 'Plan', plans: 'Essenspläne', events: 'Anlässe', home: 'Startseite', legacy: 'Gespeicherte bisherige Pläne',
    appearanceTitle: 'Kontodarstellung', appearanceAccount: 'Angemeldet werden Sprache und Design im Konto gespeichert. Gasteinstellungen bleiben auf diesem Gerät.', appearanceReview: 'Kontodarstellung prüfen', appearanceOtherSave: 'Schließe den offenen Speicherversuch in Planung oder Einkauf ab, bevor du Kontoeinstellungen änderst.', appearanceRetryChange: 'Lade deine gespeicherten Einstellungen neu. Schließe dann dieses Fenster und wähle die Änderung erneut.',
    foundation: 'Grundlage für deine Planung', foundationBody: 'Deine Pläne, Einkaufslisten und Vorlagen sind privat und werden in deinem Konto gespeichert. Wähle Gerichte, sobald veröffentlichte Katalogeinträge verfügbar sind. Geführtes Kochen aus einer geplanten Konfiguration ist noch nicht verfügbar.',
    foundationSummary: 'Über deine private Planung', language: 'Sprache', theme: 'Darstellung', light: 'Hell', dark: 'Dunkel',
    period_current: 'Aktuell', period_upcoming: 'Demnächst', period_past: 'Vergangen',
    shoppingCapacity: 'Diese Änderung würde deine gespeicherten Einkaufsauswahlen zu groß machen. Es wurde nichts geändert. Entferne eine alte Auswahl oder wähle weniger Mahlzeiten und versuche es erneut. Deine Pläne bleiben gespeichert.',
    shopping: 'Einkauf', templates: 'Vorlagen', templateName: 'Name der Vorlage', templateSave: 'Als Vorlage speichern', templateApply: 'Aus Vorlage hinzufügen', templateManage: 'Vorlagen verwalten', templateEmpty: 'Noch keine gespeicherten Vorlagen.', templateChoose: 'Gespeicherte Vorlage wählen', templateIndependent: 'Fügt unabhängige Kopien hinzu. Daten, Verknüpfungen, Erinnerungen und Einkaufsmarkierungen werden nicht kopiert.',
    'template.delete': 'Vorlage löschen', 'template.rename': 'Vorlage umbenennen', 'shopping.personal.delete': 'Einkaufseintrag entfernen',
    moveEffect: 'Die Mahlzeit wird auf das gewählte Datum verschoben. Einkaufs-Auswahlen mit ungültigen Planverweisen werden entfernt; Rückgängig stellt ihren gespeicherten Zustand wieder her.',
    personalDeleteEffect: 'Nur der gewählte eigene Einkaufseintrag wird entfernt. Die übrigen Einkaufs-Auswahlen bleiben erhalten.',
    shoppingSnapshotEffect: 'Diese gespeicherten Auswahlen werden für Rückgängig aufbewahrt. Gültige Auswahlen werden neu berechnet; ungültige Auswahlen samt Markierungen, Extras und eigenen Einträgen werden entfernt.',
    effectsShopping_scopes: 'Gespeicherte Einkaufs-Auswahlen', effectsTemplates: 'Vorlagen', unit_taste: 'nach Geschmack',
    shoppingSelectionsRemoved: 'Entfernte Einkaufs-Auswahlen', shoppingSelectionLoss: 'Diese Auswahlen sind danach nicht mehr gültig. Ihre Markierungen, Extras und eigenen Einträge werden ebenfalls entfernt. Rückgängig stellt sie gemeinsam wieder her.',
    shoppingSelectionCounts: '{checks} gespeicherte Markierungen · {extras} Extras · {personal} eigene Einträge',
    'shopping.scope.delete': 'Gespeicherte Einkaufs-Auswahl entfernen', scopeDeleteEffect: 'Nur diese Einkaufs-Auswahl wird entfernt. Plan, Anlass und Rezepte bleiben unverändert.',
    'item.create': 'Eintrag hinzufügen', 'item.update': 'Eintrag bearbeiten', 'item.delete': 'Eintrag entfernen', 'item.move': 'Eintrag verschieben', 'item.copy': 'Eintrag kopieren',
    'plan.copy': 'Erneut planen', 'event.copy': 'Anlass wiederholen',
    planAgainNote: 'Erstellt einen unabhängigen Plan ab deinem gewählten Tag. Mahlzeiten und verknüpfte Anlässe werden neue Kopien; Erinnerungen zur Vorbereitung sind wieder offen. Das Original bleibt unverändert.',
    eventAgainNote: 'Erstellt einen unabhängigen Anlass mit Menü und Gästezahl. Erinnerungen zur Vorbereitung sind wieder offen; Planverknüpfungen werden nicht übernommen. Das Original bleibt unverändert.',
    account_deleted: 'Dieses Konto wurde gelöscht. Das Speichern der Planung ist gesperrt. Kehre zu den Kontoeinstellungen zurück, um den Kontostatus zu prüfen.',
    account_deletion_pending: 'Der Ausgang der Kontolöschung ist unklar. Das Speichern der Planung ist gesperrt; unklare Speicherversuche bleiben erhalten. Prüfe die Löschung in den Kontoeinstellungen.',
    reviewAccountSettings: 'Kontoeinstellungen prüfen',
    itemKind: 'Was möchtest du hinzufügen?', menu: 'Menü', publishedDish: 'Veröffentlichtes Gericht', dishOption: 'Rezeptoption',
    catalogEmpty: 'In dieser Sprache sind keine veröffentlichten Gerichte verfügbar. Du kannst einen eigenen Eintrag oder eine Notiz hinzufügen.',
    catalogUnavailable: 'Dieses Gericht oder diese Option ist nicht verfügbar. Deine gespeicherte Referenz bleibt erhalten; es wurde kein Ersatz ausgewählt.',
    loadingItems: 'Wird geladen…', retryRead: 'Einzelheiten neu laden', itemPreview: 'Gerichtvorschau', authoredPreview: 'Veröffentlichten Inhalt ansehen',
    authoredFor: 'Veröffentlichte Mengen für', resolvedFor: 'Gespeicherte Mengen für', servings: 'Portionen', servingsCount: 'Portionen', guestsCount: 'Gäste', followsGuests: 'Gästezahl übernehmen',
    servingsInvalid: 'Gib eine ganze Portionszahl von 1 bis 1000 ein.', quantityInvalid: 'Gib Menge und Einheit zusammen an oder leere beide Felder. Die Menge muss positiv sein, höchstens 1.000.000 betragen und darf bis zu drei Nachkommastellen haben.',
    optionalQuantity: 'Menge (optional)', unit: 'Einheit', optionalGroup: 'Gruppe (optional)', contribution: 'Mitgebracht von / Beitrag (optional)',
    contributionHelp: 'Ein benannter Beitrag wird von deiner Einkaufsliste ausgeschlossen.', contributionExcluded: 'Beitrag; von deinem Einkauf ausgeschlossen',
    destinationType: 'Zieltyp', itemDestination: 'Zielmahlzeit oder Anlass', noItemTargets: 'Wähle einen Plan mit einer Mahlzeit oder einen Anlass. Erstelle bei Bedarf zuerst ein Ziel.',
    itemTransferNote: 'Wähle das Ziel ausdrücklich. Beim Verschieben in eine Mahlzeit bleiben die gespeicherten Portionen erhalten; die Gästezahl wird nicht mehr übernommen.',
    ingredients: 'Zutaten', equipment: 'Kochgeschirr', method: 'Zubereitung', minutes: 'Minuten',
    planningExample: 'Planungsbeispiel: Mengen zur Veranschaulichung, keine Kochanleitung.', previewOnly: 'Nur Vorschau. Geführtes Kochen aus dieser Konfiguration ist noch nicht verfügbar.',
    unit_piece: 'Stück', unit_head: 'Köpfe', unit_loaf: 'Laibe', unit_bunch: 'Bund', unit_pack: 'Packungen', unit_tsp: 'TL', unit_tbsp: 'EL',
    formChanged: 'Die Planung hat sich geändert, während das Formular offen war. Deine Eingaben bleiben erhalten. Prüfe vor dem Speichern die zuletzt gespeicherten Werte.',
    latestValues: 'Zuletzt gespeicherte Werte', reviewLatest: 'Meine Eingaben mit dem neuesten Stand weiterbearbeiten',
    loading: 'Deine Pläne werden geladen…', signIn: 'Melde dich an, um deine privaten Pläne zu öffnen.', signInAction: 'Anmelden',
    reload: 'Pläne neu laden', saved: 'In deinem Konto gespeichert.', saving: 'Wird gespeichert…', cancel: 'Abbrechen', close: 'Schließen', save: 'Änderungen speichern',
    backPlans: 'Alle Essenspläne', backEvents: 'Alle Anlässe', emptyPlans: 'Platz für ein paar Mahlzeiten.', emptyPlansBody: 'Wähle deine Daten und füge Mahlzeiten hinzu, wann du sie brauchst.',
    emptyEvents: 'Plane deinen nächsten Anlass.', emptyEventsBody: 'Wähle ein Datum und halte deine Vorbereitung an einem Ort fest.',
    'plan.create': 'Neuer Essensplan', 'plan.rename': 'Plan umbenennen', 'plan.resize': 'Daten ändern', 'plan.delete': 'Plan löschen',
    'meal.create': 'Mahlzeit hinzufügen', 'meal.update': 'Mahlzeit bearbeiten', 'meal.move': 'Mahlzeit verschieben', 'meal.copy': 'Mahlzeit kopieren', 'meal.delete': 'Mahlzeit löschen',
    'event.create': 'Neuer Anlass', 'event.update': 'Anlass bearbeiten', 'event.link': 'Anlass mit Plan verknüpfen', 'event.delete': 'Anlass löschen', 'event.unlink': 'Verknüpfung lösen',
    'task.create': 'Erinnerung hinzufügen', 'task.update': 'Erinnerung bearbeiten', 'task.delete': 'Erinnerung löschen',
    name: 'Name', optionalName: 'Name der Mahlzeit (optional)', start_date: 'Erster Tag', end_date: 'Letzter Tag', date: 'Datum', time: 'Uhrzeit (optional)', guests: 'Gäste',
    plan_id: 'Essensplan', event_id: 'Anlass', text: 'Erinnerung', bucket: 'Wann', done: 'Erledigt', earlier: 'Im Voraus', day: 'Am Tag', serving: 'Vor dem Servieren',
    preparation: 'Vorbereitung', preparationNote: 'Persönliche Erinnerungen für den Anlass. Hake sie ab, sobald sie erledigt sind.', noTasks: 'Hier gibt es noch keine Erinnerungen.',
    meal: 'Mahlzeit', openDay: 'Platz für etwas Gutes.', mealFoundation: 'Rezepte und Gerichte folgen als Nächstes.',
    previous: 'Vorherige drei Tage', next: 'Nächste drei Tage', dateNavigation: 'Plandaten', jump: 'Zum Datum', actions: 'Aktionen',
    outside: 'Verknüpfte Anlässe außerhalb dieser Daten', linkedEvent: 'Verknüpfter Anlass', eventIdentity: 'Dies ist überall derselbe Anlass. Änderungen gelten in allen verknüpften Plänen.',
    noTargets: 'Erstelle zuerst einen Essensplan und einen Anlass, um sie zu verknüpfen.', noPlans: 'Erstelle zuerst einen Zielplan.', choose: 'Auswählen…',
    review: 'Änderung prüfen', reviewBody: 'Diese Einträge sind genau von der Änderung betroffen.', confirm: 'Änderung bestätigen',
    effectsPlans: 'Pläne', effectsMeals: 'Mahlzeiten', effectsEvents: 'Anlässe', effectsLinks: 'Verknüpfungen', effectsTasks: 'Erinnerungen', effectsItems: 'Einträge und Notizen',
    kind_dish: 'Gericht', kind_personal: 'Eigener Eintrag', kind_note: 'Notiz',
    preserved: 'Die verknüpften Anlässe selbst bleiben erhalten.', outsidePreview: 'Verknüpfte Anlässe außerhalb der neuen Daten', recordDetails: 'Einzelheiten zum Eintrag',
    resizeEffect: 'Die Plandaten ändern sich. Die unten aufgeführten Mahlzeiten werden entfernt; Verknüpfungen bleiben erhalten.', deleteEffect: 'Die aufgeführten Einträge werden entfernt.',
    expires: 'Prüfung gültig bis', stalePreview: 'Diese Prüfung ist abgelaufen oder die Planung hat sich geändert. Schließe sie, lade neu und prüfe erneut.',
    undo: 'Rückgängig', undoNote: 'Bis zur nächsten Änderung oder bis zur angezeigten Ablaufzeit verfügbar.',
    pending: 'Der Ausgang des letzten Speicherns ist unklar. Wiederhole denselben Versuch, um festzustellen, ob er abgeschlossen wurde.',
    rejected: 'Das letzte Speichern wurde abgelehnt. Prüfe die Einzelheiten, verwirf den Versuch und lade neu, bevor du eine neue Änderung machst.',
    retry: 'Denselben Speicherversuch wiederholen', discard: 'Abgelehnten Versuch verwerfen und neu laden', pendingDetails: 'Gesendete Änderung prüfen',
    request: 'Änderung', status: 'Antwortstatus', error: 'Die Anfrage konnte nicht abgeschlossen werden. Lade neu und versuche es erneut.',
    storageError: 'Der Speicher zur Wiederherstellung ist nicht verfügbar oder unlesbar. Speichern ist gesperrt; deine gespeicherten Pläne bleiben in deinem Konto.',
    revisionError: 'Die Planung hat sich beim Laden geändert. Lade sie vor dem Bearbeiten vollständig neu.',
    lockError: 'Ein anderer Tab speichert gerade. Warte, bis er fertig ist, und lade dann neu.', lockUnavailable: 'Dieser Browser kann das Speichern zwischen Tabs nicht sicher abstimmen. Verwende einen Browser mit Web-Locks-Unterstützung.',
    sessionError: 'Deine Sitzung hat sich geändert oder ist abgelaufen. Melde dich erneut an.',
    required: 'Gib einen Namen oder eine Erinnerung ein.', range: 'Wähle einen Zeitraum von 1 bis 730 Tagen.', invalid_date: 'Wähle ein gültiges Datum.',
    notFound: 'Dieser Plan oder Anlass ist nicht mehr verfügbar.', review_required: 'Das Speichern wurde abgelehnt. Prüfe unten die gesendete Änderung, bevor du den abgelehnten Versuch verwirfst. Deine Formulareingaben bleiben erhalten.',
    previewUnsupported: 'Änderungsprüfungen sind noch nicht verfügbar. Lade nach der Planungsaktualisierung neu.',
    localFields: 'Prüfe die Felder unten. Gespeichert wird erst nach Bestätigung durch den Server.',
  },
};

export function errorText(error, t) {
  const code = error?.code || error?.message;
  if ((error?.data?.code || code) === 'shopping_capacity_exceeded') return t.shoppingCapacity;
  if (['storage_blocked', 'outbox_changed'].includes(code)) return t.storageError;
  if (['revision_changed', 'revision_conflict', 'preview_expired', 'undo_expired'].includes(error?.data?.code || code)) return t.revisionError;
  if (['stale_session', 'unauthenticated', 'session_unavailable'].includes(code) || [401, 403, 422].includes(error?.status)) return t.sessionError;
  if (code === 'writer_busy') return t.lockError;
  if (code === 'write_coordination_unavailable') return t.lockUnavailable;
  if (['catalog_unavailable', 'catalog_integrity_error'].includes(error?.data?.code || code)) return t.catalogUnavailable;
  return t[code] || t.error;
}
