export const shoppingStrings = {
  en: {
    title: 'Shopping list', chooseList: 'Choose a list', changeSelection: 'Dates & meals', view: 'View', legacyGroceries: 'Legacy groceries',
    removeSelection: 'Remove saved selection', selectionActions: 'Saved selection actions',
    rememberSelection: 'Remember this selection', rememberReview: 'Your selection was saved. Review before making it the list that opens next time; your saved preferences may have changed.',
    outsideSelection: 'Outside this plan; no shopping demand', unavailableContent: 'Some dishes are unavailable. The complete shopping list cannot be shown. Review the plan or choose another selection.', remaining: '{remaining} remaining of {total}',
    category: 'Category', alphabetical: 'A–Z', dish: 'Dish', amount: 'Amount', total: 'Total',
    ingredients: 'Ingredients', personal: 'Personal additions', extras: 'Extras', extra: 'Extra',
    category_produce: 'Fruit & vegetables', category_bakery: 'Bakery', category_cupboard: 'Cupboard', category_herbs: 'Herbs & spices', category_chilled: 'Chilled', category_frozen: 'Frozen', category_other: 'Other',
    weight: 'Weight', count: 'Count', otherAmounts: 'Other amounts', toTaste: 'To taste', unquantified: 'No quantity',
    details: 'Details', sources: 'Sources', alsoIn: 'Also in', have: 'Already have', bought: 'Bought', needed: 'Need to buy', covered: 'Covered', partial: 'Partly covered', review: 'Check amount',
    cupboardHint: 'Check your cupboard before buying', changeAmount: 'Change amount', amountLabel: 'Shopping total', minimum: 'Minimum', resetMinimum: 'Reset to the required amount.',
    invalidAmount: 'Enter a valid total with up to three decimal places, at least the required amount.',
    checkAll: 'Check all', checkAllLabel: 'Check the whole total', checkedDish: 'Checked for this dish.', checkedAll: 'Checked for the whole list.', dismiss: 'Dismiss', checkExtra: 'Check extra', removeExtra: 'Remove extra',
    undoStatus: 'Undo check', addPersonal: 'Add a personal item', editPersonal: 'Edit personal item', removePersonal: 'Remove personal item', itemName: 'Item name', optionalAmount: 'Quantity (optional)', noUnit: 'No unit',
    invalidTitle: 'Enter a name of up to 160 characters.', invalidPersonalAmount: 'Enter a positive quantity and unit, or clear both.',
    all: 'Whole list', dates: 'Date range', meals: 'Selected meals & events', from: 'From', to: 'To', twoDays: '2 days from start', applySelection: 'Apply selection',
    selectionHelp: 'Each selection keeps its own checks and additions.', selectionPreview: 'This changes the shopping selection, not the plan dates.',
    noChoices: 'No meals or events in this plan.', emptySelection: 'No meals or events selected', selected: 'Selected meals & events', chooseOwner: 'Choose a plan or event.',
    invalidSelection: 'This selection is no longer available. Reload and review it.', invalidDates: 'Choose valid dates within the plan.',
    emptyList: 'Nothing on this shopping list.', noList: 'Choose a plan or event to make a shopping list.', noOwners: 'Create a plan or event to start a list.', unavailableList: 'This shopping list is unavailable. Choose a list or reload.',
    reviewLatest: 'Review current quantities', changedDraft: 'The saved list changed. Your input is kept. Review the current quantities before saving.', missingRow: 'This item is no longer in the list. Your unsaved input is kept.',
    'shopping.scope': 'Change shopping selection', 'shopping.cover': 'Update shopping check', 'shopping.extra': 'Change extra amount',
    'shopping.personal.create': 'Add personal item', 'shopping.personal.update': 'Edit personal item', 'shopping.personal.delete': 'Remove personal item', 'preferences.update': 'Save preferences',
    effectsShoppingPersonal: 'Personal additions', effectsShoppingScopes: 'Shopping selections', effectsShopping: 'Shopping',
    unit_g: 'g', unit_kg: 'kg', unit_ml: 'ml', unit_l: 'l', unit_piece: 'pieces', unit_head: 'heads', unit_loaf: 'loaves', unit_bunch: 'bunches', unit_pack: 'packs', unit_bottle: 'bottles', unit_tsp: 'tsp', unit_tbsp: 'tbsp',
    unit_piece_one: 'piece', unit_head_one: 'head', unit_loaf_one: 'loaf', unit_bunch_one: 'bunch', unit_pack_one: 'pack', unit_bottle_one: 'bottle',
  },
  de: {
    title: 'Einkaufsliste', chooseList: 'Liste auswählen', changeSelection: 'Tage & Mahlzeiten', view: 'Ansicht', legacyGroceries: 'Bisheriger Einkauf',
    removeSelection: 'Gespeicherte Auswahl entfernen', selectionActions: 'Aktionen für die gespeicherte Auswahl',
    rememberSelection: 'Diese Auswahl merken', rememberReview: 'Deine Auswahl wurde gespeichert. Prüfe sie, bevor sie beim nächsten Öffnen angezeigt wird; deine gespeicherten Einstellungen könnten sich geändert haben.',
    outsideSelection: 'Außerhalb des Plans; kein Einkaufsbedarf', unavailableContent: 'Einige Gerichte sind nicht verfügbar. Die vollständige Einkaufsliste kann nicht angezeigt werden. Prüfe den Plan oder wähle eine andere Auswahl.', remaining: '{remaining} offen von {total}',
    category: 'Kategorie', alphabetical: 'A–Z', dish: 'Gericht', amount: 'Menge', total: 'Gesamt',
    ingredients: 'Zutaten', personal: 'Eigene Ergänzungen', extras: 'Extras', extra: 'Extra',
    category_produce: 'Obst & Gemüse', category_bakery: 'Backwaren', category_cupboard: 'Vorratsschrank', category_herbs: 'Kräuter & Gewürze', category_chilled: 'Kühlregal', category_frozen: 'Tiefkühlregal', category_other: 'Sonstiges',
    weight: 'Gewicht', count: 'Stückzahl', otherAmounts: 'Weitere Mengen', toTaste: 'Nach Geschmack', unquantified: 'Ohne Mengenangabe',
    details: 'Details', sources: 'Quellen', alsoIn: 'Auch in', have: 'Schon vorhanden', bought: 'Gekauft', needed: 'Noch kaufen', covered: 'Abgedeckt', partial: 'Teilweise abgedeckt', review: 'Menge prüfen',
    cupboardHint: 'Vor dem Einkauf den Vorratsschrank prüfen', changeAmount: 'Menge ändern', amountLabel: 'Einkaufsmenge', minimum: 'Mindestmenge', resetMinimum: 'Auf die benötigte Menge zurückgesetzt.',
    invalidAmount: 'Gib eine gültige Gesamtmenge mit höchstens drei Nachkommastellen ein, mindestens die benötigte Menge.',
    checkAll: 'Alles abhaken', checkAllLabel: 'Die gesamte Menge abhaken', checkedDish: 'Für dieses Gericht abgehakt.', checkedAll: 'Für die gesamte Liste abgehakt.', dismiss: 'Schließen', checkExtra: 'Extra abhaken', removeExtra: 'Extra entfernen',
    undoStatus: 'Abhaken rückgängig', addPersonal: 'Eigenen Artikel ergänzen', editPersonal: 'Eigenen Artikel bearbeiten', removePersonal: 'Eigenen Artikel entfernen', itemName: 'Artikelname', optionalAmount: 'Menge (optional)', noUnit: 'Keine Einheit',
    invalidTitle: 'Gib einen Namen mit höchstens 160 Zeichen ein.', invalidPersonalAmount: 'Gib eine positive Menge und eine Einheit ein oder leere beide Felder.',
    all: 'Ganze Liste', dates: 'Zeitraum', meals: 'Ausgewählte Mahlzeiten & Events', from: 'Von', to: 'Bis', twoDays: '2 Tage ab Start', applySelection: 'Auswahl übernehmen',
    selectionHelp: 'Jede Auswahl behält ihre eigenen Häkchen und Ergänzungen.', selectionPreview: 'Das ändert die Einkaufsauswahl, nicht die Daten des Plans.',
    noChoices: 'Dieser Plan enthält keine Mahlzeiten oder Events.', emptySelection: 'Keine Mahlzeiten oder Events ausgewählt', selected: 'Ausgewählte Mahlzeiten & Events', chooseOwner: 'Wähle einen Plan oder ein Event.',
    invalidSelection: 'Diese Auswahl ist nicht mehr verfügbar. Lade neu und prüfe sie.', invalidDates: 'Wähle gültige Daten innerhalb des Plans.',
    emptyList: 'Auf dieser Einkaufsliste steht noch nichts.', noList: 'Wähle einen Plan oder ein Event für deine Einkaufsliste.', noOwners: 'Erstelle einen Plan oder ein Event für deine erste Liste.', unavailableList: 'Diese Einkaufsliste ist nicht verfügbar. Wähle eine Liste oder lade neu.',
    reviewLatest: 'Aktuelle Mengen prüfen', changedDraft: 'Die gespeicherte Liste wurde geändert. Deine Eingabe bleibt erhalten. Prüfe vor dem Speichern die aktuellen Mengen.', missingRow: 'Dieser Artikel steht nicht mehr auf der Liste. Deine ungespeicherte Eingabe bleibt erhalten.',
    'shopping.scope': 'Einkaufsauswahl ändern', 'shopping.cover': 'Einkaufshäkchen ändern', 'shopping.extra': 'Extramenge ändern',
    'shopping.personal.create': 'Eigenen Artikel ergänzen', 'shopping.personal.update': 'Eigenen Artikel bearbeiten', 'shopping.personal.delete': 'Eigenen Artikel entfernen', 'preferences.update': 'Einstellungen speichern',
    effectsShoppingPersonal: 'Eigene Ergänzungen', effectsShoppingScopes: 'Einkaufsauswahl', effectsShopping: 'Einkauf',
    unit_g: 'g', unit_kg: 'kg', unit_ml: 'ml', unit_l: 'l', unit_piece: 'Stück', unit_head: 'Köpfe', unit_loaf: 'Laibe', unit_bunch: 'Bund', unit_pack: 'Packungen', unit_bottle: 'Flaschen', unit_tsp: 'TL', unit_tbsp: 'EL',
    unit_piece_one: 'Stück', unit_head_one: 'Kopf', unit_loaf_one: 'Laib', unit_bunch_one: 'Bund', unit_pack_one: 'Packung', unit_bottle_one: 'Flasche',
  },
};
